from pathlib import Path
import unittest


class KioskTest(unittest.TestCase):
    def test_server_html_contains_five_button_navigation_hooks(self):
        html = Path("chessboard_app/server.py").read_text(encoding="utf-8")

        self.assertIn("kioskState", html)
        self.assertIn("renderScreen", html)
        self.assertIn("renderWifiList", html)
        self.assertIn("renderWifiPassword", html)
        self.assertIn("PASSWORD_ROWS", html)
        for symbol in ["!", "@", "#", "$", "%", "^", "&", "*", "?"]:
            self.assertIn(f'"{symbol}"', html)
        self.assertIn("activateSelected", html)
        self.assertIn("goBack", html)
        self.assertIn("/auth/lichess/start", html)
        self.assertIn("Connect Lichess", html)
        self.assertIn("renderWifiStatus", html)
        self.assertIn("wifiSignalBars", html)
        self.assertIn("Wi-Fi:", html)
        self.assertIn("Lichess:", html)
        self.assertNotIn("Open OAuth Here", html)
        self.assertIn("Choose Wi-Fi", html)
        self.assertIn("No password needed", html)
        self.assertIn("network.security", html)
        self.assertIn("state.wifi.connected", html)
        self.assertIn('state.wifi.mode === "wired"', html)
        self.assertIn("Board Test", html)
        self.assertIn("LED Test", html)
        self.assertIn("/api/led/test", html)
        self.assertIn("activeControlRoot", html)
        self.assertIn('stage === "wifi"', html)
        self.assertIn("/api/phone-setup-qr.svg", html)
        self.assertNotIn('<img alt="Board setup network QR code"', html)
        self.assertNotIn('<img alt="Board setup page QR code"', html)
        self.assertNotIn('id="mainWifiSsidDisplay" type="text"', html)
        self.assertNotIn("activateRelativeTab", html)
        self.assertNotIn('class="tabButton"', html)
        self.assertNotIn("?.", html)
        self.assertNotIn("=>", html)
        self.assertNotIn("`", html)
        self.assertNotIn("const ", html)
        self.assertNotIn("let ", html)
        self.assertNotIn("async function", html)
        self.assertIn("renderBootError", html)
        self.assertIn("Online Games", html)
        self.assertIn("onlineMenu", html)
        online_menu = html.split("var onlineMenu = [", 1)[1].split("];", 1)[0]
        self.assertNotIn("Blitz 3+0", online_menu)
        self.assertNotIn("Blitz 3+2", online_menu)
        self.assertNotIn("Blitz 5+2", online_menu)
        self.assertNotIn("Blitz 5+3", online_menu)
        self.assertIn("Rapid 10+0", online_menu)
        self.assertIn("Classical 15+10", online_menu)
        self.assertIn("Challenge Link", online_menu)
        self.assertIn("challengeMenu", html)
        challenge_menu = html.split("var challengeMenu = [", 1)[1].split("];", 1)[0]
        self.assertIn("Blitz 3+0", challenge_menu)
        self.assertIn("Blitz 3+2", challenge_menu)
        self.assertIn("Blitz 5+0", challenge_menu)
        self.assertIn("Blitz 5+2", challenge_menu)
        self.assertIn("Blitz 5+3", challenge_menu)
        self.assertIn("startChallengeLink", html)
        self.assertIn("/api/play/open", html)
        self.assertIn("challengeUrl", html)
        self.assertIn("challengeId", html)
        self.assertIn("renderChallengeWait", html)
        self.assertIn("cancelChallengeLink", html)
        self.assertIn("/api/play/challenge/cancel", html)
        self.assertIn("Cancel Challenge", html)
        self.assertIn("moveGridSelection", html)
        self.assertIn("gridColumnsForScreen", html)
        self.assertIn("selectedClass(actionStart + i)", html)
        self.assertIn("/api/play/friend", html)
        self.assertIn("Play Computer", html)
        self.assertIn("computerMenu", html)
        self.assertIn("computerLevelMenu", html)
        self.assertIn("selectedComputerTime", html)
        self.assertIn("Choose Time", html)
        self.assertIn("Choose Level", html)
        computer_menu = html.split("var computerMenu = [", 1)[1].split("];", 1)[0]
        self.assertNotIn("1+0 Bullet", computer_menu)
        self.assertNotIn("startComputerTime(60, 0", computer_menu)
        self.assertIn("startComputerTime(180, 0", html)
        self.assertIn("startComputerTime(180, 2", html)
        self.assertIn("startComputerTime(300, 0", html)
        self.assertIn("startComputerTime(300, 2", html)
        self.assertIn("startComputerTime(300, 3", html)
        self.assertIn("startComputerTime(600, 0", html)
        self.assertIn("startComputerTime(900, 10", html)
        self.assertIn("startComputerGame(1)", html)
        self.assertIn("startComputerGame(8)", html)
        self.assertIn("finishComputerStart", html)
        self.assertIn("pendingStartPayload", html)
        self.assertIn("onlineWait", html)
        self.assertIn("renderOnlineWait", html)
        self.assertIn("Waiting for Lichess pairing", html)
        self.assertIn("stopOnlineWait", html)
        self.assertIn('!game.id && game.status === "idle"', html)
        self.assertIn("/api/game/submit-physical", html)
        self.assertIn("/api/game/refresh", html)
        self.assertIn("Submit Move", html)
        self.assertIn("Refresh Lichess", html)
        self.assertIn("Offer/Accept Draw", html)
        self.assertIn("Decline Draw", html)
        self.assertIn("Resign", html)
        self.assertIn("Confirm Resign", html)
        self.assertIn("/api/game/draw/yes", html)
        self.assertIn("/api/game/draw/no", html)
        self.assertIn("/api/game/resign", html)
        self.assertIn("pollLichessGame", html)
        self.assertIn("setInterval(pollLichessGame, 2000)", html)
        self.assertIn("renderPositionBoard(game.pieces", html)
        self.assertIn("renderGameStatusBanner", html)
        self.assertIn("setCompactBoardChrome", html)
        self.assertIn("compactBoardChrome", html)
        self.assertIn("#kioskRoot.compactBoardChrome", html)
        self.assertIn("gameStatusBanner", html)
        self.assertIn("gameStatusText", html)
        self.assertIn("Calibrating board", html)
        self.assertIn("You won", html)
        self.assertIn("You lost", html)
        self.assertIn("Draw", html)
        self.assertIn("Opponent resigned", html)
        self.assertIn("You resigned", html)
        self.assertIn("Game aborted", html)
        self.assertIn("Main Menu", html)
        self.assertIn("leaveFinishedGame", html)
        self.assertIn("/api/game/leave-finished", html)
        self.assertIn("isGameOver", html)
        self.assertIn("moveSquares.length ? moveSquares[moveSquares.length - 1]", html)
        self.assertIn("function pieceSvg(piece, playerColor)", html)
        self.assertIn("piece-blue", html)
        self.assertIn("piece-yellow", html)
        self.assertIn("svgPiece", html)
        self.assertIn("function squareCoordinateLabels(square, row, col)", html)
        self.assertIn("grid-template-rows: repeat(8, 1fr)", html)
        self.assertIn("aspect-ratio: 1", html)
        self.assertIn("min-width: 0", html)
        self.assertIn("min-height: 0", html)
        self.assertIn("overflow: hidden", html)
        self.assertIn("coord fileCoord", html)
        self.assertIn("coord rankCoord leftRank", html)
        self.assertIn("coord rankCoord rightRank", html)
        self.assertIn("squareCoordinateLabels(square, row, col)", html)
        self.assertNotIn("boardFrame", html)
        self.assertNotIn("fileLabels", html)
        self.assertNotIn("rankLabels", html)
        self.assertNotIn("translateY(-25px)", html)
        self.assertIn("♞", html)
        self.assertIn("pieceScale(piece)", html)
        self.assertIn("P: {size: 72, y: 71}", html)
        self.assertIn("B: {size: 92, y: 79}", html)
        self.assertIn("return scales[piece] || {size: 82, y: 76}", html)
        self.assertIn("♔", html)
        self.assertIn("♛", html)
        self.assertIn("renderPuzzle", html)
        self.assertIn("New Puzzle", html)
        self.assertIn("Daily Puzzle", html)
        self.assertIn("Start Puzzle", html)
        self.assertIn("Submit Puzzle Move", html)
        self.assertIn("Refresh Puzzle", html)
        self.assertIn("/api/puzzle/start", html)
        self.assertIn("/api/puzzle/submit-physical", html)
        self.assertIn("Lights Off", html)
        self.assertIn("Brightness Down", html)
        self.assertIn("/api/live-state", html)
        self.assertIn("refreshLive", html)
        self.assertIn("isLiveScreen", html)
        render_game = html.split("function renderGame()", 1)[1].split("function renderGameStatusBanner", 1)[0]
        self.assertNotIn("gameHelpText(sync)", render_game)
        self.assertIn("pendingMoveText + actionHtml", render_game)
        self.assertIn("autoSubmitDetectedMove", html)
        self.assertIn("autoSubmitMoveKey", html)
        self.assertIn("latestState.submitMoveEnabled", html)
        self.assertIn("clockTime { font-size: clamp(20px, 7vw, 34px)", html)

        self.assertIn("setInterval(refreshLive, 60)", html)
        self.assertIn("scrollSelectedIntoView", html)
        self.assertIn("scrollIntoView", html)
        self.assertIn("requestAnimationFrame(scrollSelectedIntoView)", html)
        self.assertIn(".screen { min-height: 0; overflow: auto", html)
        self.assertIn(".list { display: grid; gap: 6px; max-height: 72vh; overflow: auto", html)

        lichess_screen = html.split("function renderLichessSetup()", 1)[1].split("function renderBoard()", 1)[0]
        self.assertIn("/api/lichess-token-qr.svg", lichess_screen)
        self.assertNotIn("Check Connection", lichess_screen)
        self.assertNotIn("Get API Key", lichess_screen)
        self.assertNotIn("Enter API Key", lichess_screen)
        self.assertNotIn("/api/lichess-manual-token-qr.svg", lichess_screen)
        self.assertNotIn("/api/phone-setup-qr.svg", lichess_screen)

    def test_systemd_services_boot_backend_and_kiosk(self):
        backend = Path("deploy/systemd/chessboard.service").read_text(encoding="utf-8")
        hotspot = Path("deploy/systemd/chessboard-hotspot.service").read_text(encoding="utf-8")
        portal = Path("deploy/systemd/chessboard-portal.service").read_text(encoding="utf-8")
        dpad = Path("deploy/systemd/chessboard-dpad.service").read_text(encoding="utf-8")
        kiosk = Path("deploy/systemd/chessboard-kiosk.service").read_text(encoding="utf-8")

        self.assertIn("run_server.py --hardware", backend)
        self.assertIn(".venv/bin/python3", backend)
        self.assertIn("User=root", backend)
        self.assertIn("--host 0.0.0.0", backend)
        self.assertNotIn("network-online.target", backend)
        self.assertIn("WantedBy=multi-user.target", backend)
        self.assertIn("ensure_wifi_or_hotspot.py", hotspot)
        self.assertIn(".venv/bin/python3", hotspot)
        self.assertIn("Before=chessboard.service", hotspot)
        self.assertIn("setup_portal.py", portal)
        self.assertIn(".venv/bin/python3", portal)
        self.assertIn("dpad_keyboard.py", dpad)
        self.assertIn(".venv/bin/python3", dpad)
        self.assertIn("User=root", dpad)
        self.assertIn("--mode http", dpad)
        self.assertIn("--kiosk", kiosk)
        self.assertIn("--password-store=basic", kiosk)
        self.assertIn("--use-mock-keychain", kiosk)
        self.assertIn("/usr/bin/curl --fail", kiosk)
        self.assertIn("/api/state", kiosk)
        self.assertIn("until /usr/bin/curl", kiosk)
        self.assertIn("--user-data-dir=/home/pi/.config/chessboard-kiosk", kiosk)
        self.assertIn("exec /usr/bin/chromium-browser", kiosk)
        self.assertNotIn("ExecStartPre", kiosk)
        self.assertIn("http://127.0.0.1:8000", kiosk)

    def test_install_script_updates_services(self):
        script = Path("deploy/install_services.sh").read_text(encoding="utf-8")

        self.assertIn(".venv/bin/python3 -m pip", script)
        self.assertIn("pip install -r requirements.txt", script)
        self.assertIn("dnsmasq-shared.d", script)
        self.assertIn("chessboard-portal.service", script)
        self.assertIn("chessboard-dpad.service", script)
        self.assertIn("modprobe uinput", script)
        self.assertIn("systemctl daemon-reload", script)
        self.assertIn("systemctl restart chessboard.service", script)


if __name__ == "__main__":
    unittest.main()
